# Generated by Django 4.0.4 on 2022-05-15 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('imageReference', models.CharField(default=None, max_length=50)),
                ('searchWord', models.CharField(max_length=50)),
                ('placeID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('name', 'NAME'), ('distance', 'DISTANCE'), ('rating', 'RATING')], default='green', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castlefinder.castle')),
            ],
        ),
        migrations.CreateModel(
            name='CastleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='castle_images/')),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castlefinder.castle')),
            ],
        ),
    ]
