# Generated by Django 4.0.4 on 2022-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlefinder', '0002_alter_castle_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castleimage',
            old_name='product',
            new_name='castle',
        ),
        migrations.RemoveField(
            model_name='castleimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='castle',
            name='imageReference',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
